"""add security settings

Revision ID: 3250333a78d3
Revises: 89a569dab95a
Create Date: 2026-08-15 21:51:17.624676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3250333a78d3'
down_revision = '89a569dab95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pw_min_length', sa.Integer(), nullable=False),
    sa.Column('pw_expiry', sa.Integer(), nullable=False),
    sa.Column('require_case', sa.Boolean(), nullable=False),
    sa.Column('require_numbers', sa.Boolean(), nullable=False),
    sa.Column('require_symbols', sa.Boolean(), nullable=False),
    sa.Column('prevent_reuse', sa.Boolean(), nullable=False),
    sa.Column('enforce_mfa', sa.Boolean(), nullable=False),
    sa.Column('max_sessions', sa.String(length=20), nullable=False),
    sa.Column('allowlist', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_settings_user_id'))

    op.drop_table('security_settings')
    # ### end Alembic commands ###
