"""add threat intelligence models

Revision ID: 36db13e6d1c3
Revises: 93487e79ddae
Create Date: 2026-09-06 11:26:55.973321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36db13e6d1c3'
down_revision = '93487e79ddae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('sophistication', sa.String(length=100), nullable=True),
    sa.Column('motivation', sa.String(length=255), nullable=True),
    sa.Column('campaign_count', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_sectors', sa.Text(), nullable=False),
    sa.Column('mitre_tactics', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_actors_actor_id'), ['actor_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_threat_actors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_actors_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_actors_last_activity'), ['last_activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_actors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_actors_origin'), ['origin'], unique=False)

    op.create_table('threat_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('first_observed', sa.DateTime(), nullable=True),
    sa.Column('target_sectors', sa.Text(), nullable=False),
    sa.Column('ioc_count', sa.Integer(), nullable=False),
    sa.Column('ttps', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_campaigns_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_campaigns_campaign_id'), ['campaign_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_threat_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_campaigns_first_observed'), ['first_observed'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_campaigns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_campaigns_status'), ['status'], unique=False)

    op.create_table('threat_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('feed_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ioc_count', sa.Integer(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('reliability', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_feeds_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_feeds_feed_id'), ['feed_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_threat_feeds_last_sync'), ['last_sync'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_feeds_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_feeds_status'), ['status'], unique=False)

    op.create_table('threat_iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('threat_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('sightings', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_iocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_iocs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_ioc_id'), ['ioc_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_threat_iocs_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_threat_level'), ['threat_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_iocs_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_iocs_value'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_type'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_threat_level'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_status'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_source'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_last_seen'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_ioc_id'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_first_seen'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_created_at'))
        batch_op.drop_index(batch_op.f('ix_threat_iocs_campaign_id'))

    op.drop_table('threat_iocs')
    with op.batch_alter_table('threat_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_feeds_status'))
        batch_op.drop_index(batch_op.f('ix_threat_feeds_name'))
        batch_op.drop_index(batch_op.f('ix_threat_feeds_last_sync'))
        batch_op.drop_index(batch_op.f('ix_threat_feeds_feed_id'))
        batch_op.drop_index(batch_op.f('ix_threat_feeds_created_at'))

    op.drop_table('threat_feeds')
    with op.batch_alter_table('threat_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_threat_campaigns_name'))
        batch_op.drop_index(batch_op.f('ix_threat_campaigns_first_observed'))
        batch_op.drop_index(batch_op.f('ix_threat_campaigns_created_at'))
        batch_op.drop_index(batch_op.f('ix_threat_campaigns_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_threat_campaigns_actor_id'))

    op.drop_table('threat_campaigns')
    with op.batch_alter_table('threat_actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_actors_origin'))
        batch_op.drop_index(batch_op.f('ix_threat_actors_name'))
        batch_op.drop_index(batch_op.f('ix_threat_actors_last_activity'))
        batch_op.drop_index(batch_op.f('ix_threat_actors_first_seen'))
        batch_op.drop_index(batch_op.f('ix_threat_actors_created_at'))
        batch_op.drop_index(batch_op.f('ix_threat_actors_actor_id'))

    op.drop_table('threat_actors')
    # ### end Alembic commands ###
