"""add incident model

Revision ID: 3fa8a3ef70cb
Revises: 9d5a36be5f9b
Create Date: 2026-08-19 13:36:59.700414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa8a3ef70cb'
down_revision = '9d5a36be5f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('detection_event_id', sa.Integer(), nullable=True),
    sa.Column('affected_host', sa.String(length=255), nullable=True),
    sa.Column('affected_asset', sa.String(length=255), nullable=True),
    sa.Column('mitre_id', sa.String(length=50), nullable=True),
    sa.Column('mitre_name', sa.String(length=255), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('containment_notes', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['detection_event_id'], ['detection_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_affected_asset'), ['affected_asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_affected_host'), ['affected_host'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_detection_event_id'), ['detection_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_incident_id'), ['incident_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_incidents_mitre_id'), ['mitre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_priority'))
        batch_op.drop_index(batch_op.f('ix_incidents_mitre_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_detection_event_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_detected_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_created_by'))
        batch_op.drop_index(batch_op.f('ix_incidents_assigned_to'))
        batch_op.drop_index(batch_op.f('ix_incidents_affected_host'))
        batch_op.drop_index(batch_op.f('ix_incidents_affected_asset'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
