"""add siem_events and siem_saved_searches tables

Revision ID: 5e13e762d828
Revises: 36db13e6d1c3
Create Date: 2026-09-06 13:24:19.228723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e13e762d828'
down_revision = '36db13e6d1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siem_saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('alerting', sa.Boolean(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siem_saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siem_saved_searches_alerting'), ['alerting'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_saved_searches_pinned'), ['pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_saved_searches_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_saved_searches_search_id'), ['search_id'], unique=True)

    op.create_table('siem_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_log', sa.Text(), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('ioc_match_id', sa.String(length=100), nullable=True),
    sa.Column('detection_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['detection_event_id'], ['detection_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siem_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siem_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_events_detection_event_id'), ['detection_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_siem_events_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_events_ioc_match_id'), ['ioc_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_siem_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siem_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siem_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_siem_events_source'))
        batch_op.drop_index(batch_op.f('ix_siem_events_severity'))
        batch_op.drop_index(batch_op.f('ix_siem_events_ioc_match_id'))
        batch_op.drop_index(batch_op.f('ix_siem_events_host'))
        batch_op.drop_index(batch_op.f('ix_siem_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_siem_events_detection_event_id'))
        batch_op.drop_index(batch_op.f('ix_siem_events_category'))

    op.drop_table('siem_events')
    with op.batch_alter_table('siem_saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siem_saved_searches_search_id'))
        batch_op.drop_index(batch_op.f('ix_siem_saved_searches_scope'))
        batch_op.drop_index(batch_op.f('ix_siem_saved_searches_pinned'))
        batch_op.drop_index(batch_op.f('ix_siem_saved_searches_alerting'))

    op.drop_table('siem_saved_searches')
    # ### end Alembic commands ###
