"""add_packet_analysis_table

Revision ID: 5f9d3615d4a6
Revises: a2f693dbc9e8
Create Date: 2026-09-08 12:25:31.951782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9d3615d4a6'
down_revision = 'a2f693dbc9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packet_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_uuid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('first_packet_time', sa.DateTime(), nullable=True),
    sa.Column('last_packet_time', sa.DateTime(), nullable=True),
    sa.Column('encapsulation', sa.String(length=64), nullable=True),
    sa.Column('protocol_stats', sa.JSON(), nullable=True),
    sa.Column('endpoint_stats', sa.JSON(), nullable=True),
    sa.Column('conversation_stats', sa.JSON(), nullable=True),
    sa.Column('summary_metadata', sa.JSON(), nullable=True),
    sa.Column('ids_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packet_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packet_analyses_analysis_uuid'), ['analysis_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_packet_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_analyses_ids_event_id'), ['ids_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_analyses_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_analyses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_packet_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packet_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packet_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_packet_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_packet_analyses_sha256'))
        batch_op.drop_index(batch_op.f('ix_packet_analyses_ids_event_id'))
        batch_op.drop_index(batch_op.f('ix_packet_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_packet_analyses_analysis_uuid'))

    op.drop_table('packet_analyses')
    # ### end Alembic commands ###
