"""add asset management

Revision ID: 78802c3c07ba
Revises: 5f9d3615d4a6
Create Date: 2026-09-08 13:35:37.433728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78802c3c07ba'
down_revision = '5f9d3615d4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('fqdn', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('owner_team', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('operating_system', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.Column('discovered_ports', sa.JSON(), nullable=True),
    sa.Column('discovered_services', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_severity', sa.String(length=32), nullable=False),
    sa.Column('open_vulnerabilities_count', sa.Integer(), nullable=False),
    sa.Column('open_alerts_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_id'), ['asset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_criticality'), ['criticality'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_risk_severity'), ['risk_severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_risk_severity'))
        batch_op.drop_index(batch_op.f('ix_assets_name'))
        batch_op.drop_index(batch_op.f('ix_assets_mac_address'))
        batch_op.drop_index(batch_op.f('ix_assets_last_seen'))
        batch_op.drop_index(batch_op.f('ix_assets_ip_address'))
        batch_op.drop_index(batch_op.f('ix_assets_hostname'))
        batch_op.drop_index(batch_op.f('ix_assets_environment'))
        batch_op.drop_index(batch_op.f('ix_assets_criticality'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
