"""create general settings table

Revision ID: 82d4d2c69504
Revises: 3354f774d769
Create Date: 2026-08-16 22:30:08.634016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d4d2c69504'
down_revision = '3354f774d769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('default_landing', sa.String(length=50), nullable=False),
    sa.Column('session_timeout', sa.Integer(), nullable=False),
    sa.Column('compact_density', sa.Boolean(), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_settings_user_id'))

    op.drop_table('general_settings')
    # ### end Alembic commands ###
