"""add detection engine

Revision ID: 9d5a36be5f9b
Revises: 82d4d2c69504
Create Date: 2026-08-19 12:38:39.764451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5a36be5f9b'
down_revision = '82d4d2c69504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('mitre_id', sa.String(length=50), nullable=True),
    sa.Column('mitre_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('triggers_30d', sa.Integer(), nullable=False),
    sa.Column('false_positive_rate', sa.Float(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('actions', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_mitre_id'), ['mitre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_rule_id'), ['rule_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_detection_rules_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_status'), ['status'], unique=False)

    op.create_table('detection_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mitre_id', sa.String(length=50), nullable=True),
    sa.Column('raw_event', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_detection_events_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_events_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_detection_events_status'))
        batch_op.drop_index(batch_op.f('ix_detection_events_severity'))
        batch_op.drop_index(batch_op.f('ix_detection_events_rule_id'))
        batch_op.drop_index(batch_op.f('ix_detection_events_host'))
        batch_op.drop_index(batch_op.f('ix_detection_events_event_id'))

    op.drop_table('detection_events')
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_status'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_severity'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_rule_id'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_mitre_id'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_category'))

    op.drop_table('detection_rules')
    # ### end Alembic commands ###
