"""add_network_ids_events_and_sensors

Revision ID: a2f693dbc9e8
Revises: e4678ce44197
Create Date: 2026-09-08 11:30:13.119149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f693dbc9e8'
down_revision = 'e4678ce44197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ids_sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('interface', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('suricata_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('eve_log_path', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ids_sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ids_sensors_sensor_id'), ['sensor_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ids_sensors_status'), ['status'], unique=False)

    op.create_table('network_ids_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_uuid', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('sensor_name', sa.String(length=100), nullable=False),
    sa.Column('interface', sa.String(length=32), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(length=64), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('app_protocol', sa.String(length=50), nullable=True),
    sa.Column('flow_id', sa.String(length=64), nullable=True),
    sa.Column('signature_id', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('raw_event_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_ids_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_ids_events_app_protocol'), ['app_protocol'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_dest_ip'), ['dest_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_dest_port'), ['dest_port'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_event_uuid'), ['event_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_network_ids_events_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_interface'), ['interface'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_protocol'), ['protocol'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_sensor_name'), ['sensor_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_signature'), ['signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_signature_id'), ['signature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_src_port'), ['src_port'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ids_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_ids_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_ids_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_src_port'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_src_ip'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_source'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_signature_id'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_signature'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_severity'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_sensor_name'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_protocol'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_interface'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_flow_id'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_event_uuid'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_dest_port'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_dest_ip'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_category'))
        batch_op.drop_index(batch_op.f('ix_network_ids_events_app_protocol'))

    op.drop_table('network_ids_events')
    with op.batch_alter_table('ids_sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ids_sensors_status'))
        batch_op.drop_index(batch_op.f('ix_ids_sensors_sensor_id'))

    op.drop_table('ids_sensors')
    # ### end Alembic commands ###
