"""add threat hunting ai assistant and soar models

Revision ID: acbe1a0c61a0
Revises: d10d6483149b
Create Date: 2026-09-08 16:02:30.991996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbe1a0c61a0'
down_revision = 'd10d6483149b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_conversation_id'), ['conversation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_conversations_created_at'), ['created_at'], unique=False)

    op.create_table('soar_playbook_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=False),
    sa.Column('playbook_name', sa.String(length=128), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_params_json', sa.Text(), nullable=True),
    sa.Column('execution_steps_json', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soar_playbook_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soar_playbook_executions_execution_id'), ['execution_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_soar_playbook_executions_playbook_id'), ['playbook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_soar_playbook_executions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_soar_playbook_executions_status'), ['status'], unique=False)

    op.create_table('threat_hunt_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hunt_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('query_text', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_hunt_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_hunt_queries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_hunt_queries_hunt_id'), ['hunt_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_threat_hunt_queries_is_saved'), ['is_saved'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('recommendations_json', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_created_at'), ['created_at'], unique=False)

    op.create_table('soar_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_name', sa.String(length=128), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.String(length=128), nullable=False),
    sa.Column('change_payload_json', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['soar_playbook_executions.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soar_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soar_approvals_approval_id'), ['approval_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_soar_approvals_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_soar_approvals_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_soar_approvals_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soar_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soar_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_soar_approvals_requested_at'))
        batch_op.drop_index(batch_op.f('ix_soar_approvals_execution_id'))
        batch_op.drop_index(batch_op.f('ix_soar_approvals_approval_id'))

    op.drop_table('soar_approvals')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('threat_hunt_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_hunt_queries_is_saved'))
        batch_op.drop_index(batch_op.f('ix_threat_hunt_queries_hunt_id'))
        batch_op.drop_index(batch_op.f('ix_threat_hunt_queries_created_at'))

    op.drop_table('threat_hunt_queries')
    with op.batch_alter_table('soar_playbook_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soar_playbook_executions_status'))
        batch_op.drop_index(batch_op.f('ix_soar_playbook_executions_started_at'))
        batch_op.drop_index(batch_op.f('ix_soar_playbook_executions_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_soar_playbook_executions_execution_id'))

    op.drop_table('soar_playbook_executions')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_conversation_id'))

    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
