"""upgrade scanner multi tool targets and findings

Revision ID: c3f119f0a977
Revises: 69b43336324f
Create Date: 2026-09-06 14:16:49.375021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f119f0a977'
down_revision = '69b43336324f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=False, server_default='Host'))
        batch_op.add_column(sa.Column('normalized_value', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dns_records_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('is_authorized', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('parsed_url_json', sa.Text(), nullable=False, server_default='{}'))

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=50), nullable=False, server_default='STANDARD'))
        batch_op.add_column(sa.Column('tools_used_json', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('dns_data_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('web_technologies_json', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('tls_summary_json', sa.Text(), nullable=False, server_default='{}'))

    with op.batch_alter_table('vulnerability_findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.String(length=50), nullable=False, server_default='nmap'))
        batch_op.add_column(sa.Column('cwe', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(length=30), nullable=False, server_default='high'))
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('threat_intel_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.create_index(batch_op.f('ix_vulnerability_findings_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_findings_tool'), ['tool'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_findings_tool'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_findings_fingerprint'))
        batch_op.drop_column('threat_intel_json')
        batch_op.drop_column('fingerprint')
        batch_op.drop_column('confidence')
        batch_op.drop_column('cwe')
        batch_op.drop_column('tool')

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('tls_summary_json')
        batch_op.drop_column('web_technologies_json')
        batch_op.drop_column('dns_data_json')
        batch_op.drop_column('tools_used_json')
        batch_op.drop_column('profile')

    with op.batch_alter_table('scan_targets', schema=None) as batch_op:
        batch_op.drop_column('parsed_url_json')
        batch_op.drop_column('is_authorized')
        batch_op.drop_column('dns_records_json')
        batch_op.drop_column('normalized_value')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
