"""add notification settings

Revision ID: c9bdea323bdd
Revises: 3250333a78d3
Create Date: 2026-08-16 21:47:45.773408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bdea323bdd'
down_revision = '3250333a78d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('slack_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_matrix', sa.Text(), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_from', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_to', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_settings_user_id'))

    op.drop_table('notification_settings')
    # ### end Alembic commands ###
