"""add service_observations to scans

Revision ID: e4678ce44197
Revises: c3f119f0a977
Create Date: 2026-09-06 15:29:22.546835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4678ce44197'
down_revision = 'c3f119f0a977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_observations_json', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('service_observations_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('service_observations_count')
        batch_op.drop_column('service_observations_json')

    # ### end Alembic commands ###
